<?php
require_once __DIR__ . '/../includes/functions.php';
require_once __DIR__ . '/../includes/auth.php';

$reference = trim($_GET['reference'] ?? '');
$card = null;

if ($reference !== '' && preg_match('/^[A-Za-z0-9\-]{4,40}$/', $reference)) {
    $stmt = get_db()->prepare('SELECT * FROM medical_cards WHERE reference_number = :ref LIMIT 1');
    $stmt->execute(['ref' => $reference]);
    $card = $stmt->fetch();
}
$base = site_base_url();
?><!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Print Medical Card — <?= h(APP_NAME) ?></title>
<link rel="stylesheet" href="<?= h($base) ?>/assets/css/print.css">
</head>
<body class="print-page">

<?php if (!$card): ?>
  <div class="alert" style="background:#fee2e2;color:#7f1d1d;padding:16px;border-radius:8px;">
    No medical card was found for this reference number.
  </div>
  <p><a href="<?= h($base) ?>/public/medical-card.php">← Back to search</a></p>
<?php else: ?>

  <div class="print-actions no-print">
    <button onclick="window.print()">🖨️ Print This Card</button>
    <a href="<?= h($base) ?>/public/medical-card.php?reference=<?= urlencode($card['reference_number']) ?>">← Back</a>
  </div>

  <div class="print-card">
    <div class="print-card-header">
      <h2>Health Vault Medical Card</h2>
      <span class="print-ref"><?= h($card['reference_number']) ?></span>
    </div>
    <dl>
      <dt>Full Name</dt><dd><?= h($card['full_name']) ?></dd>
      <dt>Date of Birth</dt><dd><?= h(format_date($card['date_of_birth'])) ?></dd>
      <dt>Gender</dt><dd><?= h($card['gender'] ?: '—') ?></dd>
      <dt>Blood Group</dt><dd><?= h($card['blood_group'] ?: '—') ?></dd>
      <dt>Contact Number</dt><dd><?= h($card['contact_number']) ?></dd>
      <dt>Email</dt><dd><?= h($card['email']) ?></dd>
      <dt>Address</dt><dd><?= h($card['address'] ?: '—') ?></dd>
      <dt>Emergency Contact</dt>
      <dd><?= h($card['emergency_contact_name'] ?: '—') ?><?= $card['emergency_contact_number'] ? ' (' . h($card['emergency_contact_number']) . ')' : '' ?></dd>
      <dt>Known Allergies</dt><dd><?= h($card['known_allergies'] ?: 'None recorded') ?></dd>
      <dt>Issued On</dt><dd><?= h(format_date($card['created_at'])) ?></dd>
    </dl>
  </div>
  <p class="print-footer">Generated by Health Vault on <?= h(date('M j, Y g:i A')) ?>. Keep this card safe.</p>

<?php endif; ?>
</body>
</html>
